=== skiff-sh/skiff/api/jsonschema/skiff.registry.v1alpha1.Package.jsonschema.strict.bundle.json
{
  "$defs": {
    "google.protobuf.ListValue.jsonschema.strict.json": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "List Value",
      "type": "array"
    },
    "google.protobuf.Value.jsonschema.strict.json": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "Value"
    },
    "skiff.registry.v1alpha1.Field.SubField.jsonschema.strict.json": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "enum": {
          "$ref": "#/$defs/google.protobuf.ListValue.jsonschema.strict.json",
          "description": "Restrict your options to a set of values to choose."
        },
        "type": {
          "description": "Required. Can be a string or number.",
          "enum": [
            "string",
            "number"
          ],
          "title": "Type",
          "type": "string"
        }
      },
      "required": [
        "type"
      ],
      "title": "Sub Field",
      "type": "object"
    },
    "skiff.registry.v1alpha1.Field.jsonschema.strict.json": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "default": {
          "$ref": "#/$defs/google.protobuf.Value.jsonschema.strict.json",
          "description": "The default value. If set, the field will be marked as optional. If the enum field is set, this field must be one of the enum values."
        },
        "description": {
          "description": "A short description of the field. This is highly recommended to provide context to all consumers of your package.",
          "type": "string"
        },
        "enum": {
          "$ref": "#/$defs/google.protobuf.ListValue.jsonschema.strict.json",
          "description": "Restrict your options to a set of values to choose."
        },
        "items": {
          "$ref": "#/$defs/skiff.registry.v1alpha1.Field.SubField.jsonschema.strict.json",
          "description": "If the type is set to \"array\", this specifies the underlying type. Required if type is \"array\"."
        },
        "name": {
          "description": "The name of the field. This must be unique between all fields.",
          "minLength": 1,
          "type": "string"
        },
        "type": {
          "description": "The expected type of the field.",
          "enum": [
            "string",
            "bool",
            "number",
            "array"
          ],
          "title": "Type",
          "type": "string"
        }
      },
      "required": [
        "name",
        "type"
      ],
      "title": "Field",
      "type": "object"
    },
    "skiff.registry.v1alpha1.File.jsonschema.strict.json": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "content": {
          "description": "The text contents of the file. This field will be populated if the file contains valid UTF-8 text. Otherwise, the contents are set in the raw field. You do not need to populate this manually.",
          "type": "string"
        },
        "path": {
          "description": "The path to the template relative to the root of the registry. The root of the registry is the directory housing your 'registry.json' file. Cannot be outside of the registry root.",
          "minLength": 1,
          "type": "string"
        },
        "raw": {
          "description": "The raw contents of the file. You do not need to populate this manually. This field is set if the data is binary. It is mutually exclusive with the content field.",
          "pattern": "^[A-Za-z0-9+/]*={0,2}$",
          "type": "string"
        },
        "target": {
          "description": "The target path of the rendered template relative to the root of the project. Accepts template parameters.",
          "minLength": 1,
          "type": "string"
        },
        "type": {
          "description": "The type of the file. Defaults to plain.",
          "enum": [
            "plain",
            "template",
            "plugin"
          ],
          "title": "Type",
          "type": "string"
        }
      },
      "required": [
        "path",
        "target",
        "type"
      ],
      "title": "File",
      "type": "object"
    },
    "skiff.registry.v1alpha1.Package.jsonschema.strict.json": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "description": {
          "description": "A short description of the purpose of this package and what it contains. Should be LLM-friendly. Supports markdown.",
          "minLength": 1,
          "type": "string"
        },
        "files": {
          "items": {
            "$ref": "#/$defs/skiff.registry.v1alpha1.File.jsonschema.strict.json"
          },
          "type": "array"
        },
        "name": {
          "description": "The name of the package. This should be unique between all packages within a registry.",
          "minLength": 1,
          "type": "string"
        },
        "schema": {
          "$ref": "#/$defs/skiff.registry.v1alpha1.Schema.jsonschema.strict.json",
          "description": "If a field does not have a default, it is marked as required."
        }
      },
      "required": [
        "name",
        "description"
      ],
      "title": "Package",
      "type": "object"
    },
    "skiff.registry.v1alpha1.Schema.jsonschema.strict.json": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "fields": {
          "items": {
            "$ref": "#/$defs/skiff.registry.v1alpha1.Field.jsonschema.strict.json"
          },
          "type": "array"
        }
      },
      "title": "Schema",
      "type": "object"
    }
  },
  "$id": "skiff.registry.v1alpha1.Package.jsonschema.strict.bundle.json",
  "$ref": "#/$defs/skiff.registry.v1alpha1.Package.jsonschema.strict.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== skiff-sh/skiff/examples/go-fiber-controller/public/r/create-http-route.json
{
  "name": "create-http-route",
  "description": "Create a Fiber route to expose via HTTP",
  "files": [
    {
      "path": "templates/controller.tmpl",
      "target": "controller/{{.name}}.go",
      "type": "template",
      "content": "package controller\n\nimport (\n\t\"net/http\"\n\n\t\"github.com/gofiber/fiber/v2\"\n)\n\nvar _ Controller = (*{{capitalize .name}}Controller)(nil)\n\ntype {{capitalize .name}}Controller struct {\n}\n\nfunc (h *Hello) Method() string {\n\treturn \"{{.method}}\"\n}\n\nfunc (h *Hello) Path() string {\n\treturn \"{{.path}}\"\n}\n\nfunc (h *Hello) Handle(c *fiber.Ctx) error {\n  return c.SendString(\"hello from \" + {{.name}})\n}\n"
    }
  ],
  "schema": {
    "fields": [
      {
        "name": "name",
        "type": "string",
        "description": "The name of your controller"
      },
      {
        "name": "method",
        "type": "string",
        "description": "The HTTP method for your controller",
        "enum": [
          "GET",
          "POST",
          "PUT",
          "DELETE",
          "HEAD",
          "CONNECT",
          "OPTIONS",
          "TRACE",
          "PATCH"
        ]
      },
      {
        "name": "path",
        "type": "string",
        "description": "The path expression for your controller"
      }
    ]
  }
}
